#!/bin/sh
#
# The committed icon set is complete and current.
#
#   tools/check-icons.sh
#
# assets/icon is generated by `make icons` from one SVG, and committed, so a
# release job needs neither librsvg nor ImageMagick. The cost of committing
# generated files is that they can go stale, or half-regenerate, and nothing
# says so - the executable and the installer just quietly ship the previous
# artwork.
#
# Checked by shape rather than by re-rendering and diffing: rendering goes
# through librsvg and a resampler, and two versions of either can disagree in
# the last bit of one antialiased pixel. That would turn a correct icon set
# into a red build, which teaches everyone to ignore this check.
#
# This lives in a script rather than inline in the workflow so it can be run
# before pushing. It was inline once, was not updated when the icons were
# renamed, and found that out on CI.

set -eu
cd "$(dirname "$0")/.."

SIZES="16 24 32 48 64 128 256 512"
ICO=assets/icon/bencsnip.ico
SRC=assets/icon/film_camera_star.svg
fail=0

[ -f "$SRC" ] || { echo "  missing $SRC - the source every icon comes from"; fail=1; }

for s in $SIZES; do
    f="assets/icon/icon-$s.png"
    if [ ! -f "$f" ]; then
        echo "  missing $f"
        fail=1
        continue
    fi
    got=$(file "$f" | sed -n "s/.*, \([0-9]*\) x \([0-9]*\).*/\1x\2/p")
    if [ "$got" != "${s}x${s}" ]; then
        echo "  $f is $got, expected ${s}x${s}"
        fail=1
    fi
done

# The .ico is opened rather than merely counted. A set where every PNG is
# present but the .ico was built from the previous artwork looks perfectly
# fine in `ls`, and ships the old icon inside the executable and the
# installer - which are the two places nobody looks until it is released.
if [ -f "$ICO" ]; then
    python3 - "$ICO" <<'PY' || fail=1
import struct, sys

want = [16, 24, 32, 48, 64, 128, 256]
data = open(sys.argv[1], "rb").read()

reserved, kind, count = struct.unpack("<HHH", data[:6])
if reserved != 0 or kind != 1:
    print(f"  {sys.argv[1]} is not an icon file", file=sys.stderr)
    sys.exit(1)

got = [data[6 + i * 16] or 256 for i in range(count)]
if got != want:
    print(f"  {sys.argv[1]} holds {got}, expected {want} - run make icons",
          file=sys.stderr)
    sys.exit(1)

print(f"  {sys.argv[1]}: {got}")
PY
else
    echo "  missing $ICO"
    fail=1
fi

[ "$fail" = 0 ] || { echo "the icon set is stale - run: make icons"; exit 1; }
echo "  icon set complete: $SIZES"
