/*
 * mkembed - turn files into a C source file
 *
 * The GUI used to look for its font on disk, which meant the font could be
 * separated from the program that needs it: unzip the archive without the
 * assets folder, make a shortcut, launch from a terminal somewhere else, and
 * the window came up in the fallback font. A file next to an executable is a
 * file that can go missing.
 *
 * So the font travels inside the binary, and so do the licences - which is not
 * an afterthought but the condition attached to doing this. The SIL Open Font
 * License permits bundling the font with software, "provided that each copy
 * contains the above copyright notice and this license... either as
 * stand-alone text files, human-readable headers or in the appropriate
 * machine-readable metadata fields within text or binary files as long as
 * those fields can be easily viewed by the user." Embedding the font and not
 * the licence would fail that. Embedding both, and giving the user a window
 * that shows them, meets it.
 *
 *   mkembed OUT.c SYMBOL FILE [SYMBOL FILE ...]
 *
 * Each pair emits SYMBOL[] and SYMBOL_LEN. The array carries a trailing NUL
 * that SYMBOL_LEN does not count, so text blobs can be used as C strings and
 * binary blobs are unaffected.
 */

#include <stdio.h>
#include <stdlib.h>

static int emit(FILE *out, const char *symbol, const char *path)
{
    FILE *in = fopen(path, "rb");
    unsigned long n = 0;
    int c;

    if (in == 0) {
        fprintf(stderr, "mkembed: cannot open %s\n", path);
        return -1;
    }

    fprintf(out, "/* %s, %s */\n", symbol, path);
    fprintf(out, "const unsigned char %s[] = {", symbol);

    while ((c = fgetc(in)) != EOF) {
        if (n % 16u == 0u) fputs("\n   ", out);
        fprintf(out, " %3d,", c & 0xff);
        n++;
    }
    fclose(in);

    /* The trailing NUL is outside the length, so a text blob is a valid C
     * string and a binary blob's length is still exactly its byte count. */
    fputs("\n      0\n};\n", out);
    fprintf(out, "const unsigned int %s_LEN = %luu;\n\n", symbol, n);

    printf("  %-18s %8lu bytes  %s\n", symbol, n, path);
    return 0;
}

int main(int argc, char **argv)
{
    FILE *out;
    int i;

    if (argc < 4 || (argc % 2) != 0) {
        fprintf(stderr, "usage: mkembed OUT.c SYMBOL FILE [SYMBOL FILE ...]\n");
        return 2;
    }

    out = fopen(argv[1], "wb");
    if (out == 0) {
        fprintf(stderr, "mkembed: cannot write %s\n", argv[1]);
        return 1;
    }

    fputs("/*\n"
          " * Generated by tools/mkembed.c - do not edit.\n"
          " *\n"
          " * Assets compiled into the GUI so they cannot be separated from it.\n"
          " * Regenerate with `make` after changing anything in assets/.\n"
          " */\n\n", out);

    for (i = 2; i + 1 < argc; i += 2) {
        if (emit(out, argv[i], argv[i + 1]) != 0) {
            fclose(out);
            remove(argv[1]);
            return 1;
        }
    }

    fclose(out);
    return 0;
}
